language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_script: 
  - composer install
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
script: php mageekguy.atoum.phar --bf ./tests/units/bootstrap.php --directories ./tests/units