<?php
namespace Tlc\ErrorHandler;

use Tlc\Component\Component;

/**
 * Description of ExceptionHandler
 *
 * @author gdievart
 */
class ErrorHandler extends Component
{
    /**
     * Catch all error generated by php interpreter
     * 
     * @param int $errno
     * @param string $message
     */
    public static function catchError($errno, $message)
    {
        echo "Error: " . $message . " (" . $errno . ")\n";
    }
}
