<?php
namespace Tlc\ErrorHandler;

use Tlc\Component\Component;
use Tlc\Conf\Conf;
use Tlc\Logger\Logger;

/**
 * Catch all error and log
 *
 * @author gdievart
 */
class ErrorHandler extends Component
{
    /**
     * Catch all error generated by php interpreter
     * 
     * @param int $errno
     * @param string $message
     */
    public static function catchError($errno, $message)
    {
        if($loggerConfig = Conf::getConfig('logger')) {
            $logger = new Logger($loggerConfig);
            $logger->log("Error: " . $message . " (" . $errno . ")\n");
        }
    }
}
