<?php
namespace Telelab\ErrorHandler;

use Telelab\Component\Component;
use Telelab\Conf\Conf;
use Telelab\Logger\Logger;

/**
 * Catch all error and log
 *
 * @author gdievart <dievartg@gmail.com>
 */
class ErrorHandler extends Component
{
    /**
     * Catch all error generated by php interpreter
     *
     * @param int    $errno
     * @param string $message
     */
    public static function catchError($errno, $message, $file, $line)
    {
        if ((boolean) Conf::getConfig('logger.enable')) {
            $message = 'Error ['.$errno.'] '.$message.' ' .
                       'in file '.$file.' on line '.$line;
            Logger::initStatic();
            Logger::log($message);
        }
    }
}
