<?php
namespace Telelab\FrontController;

use Telelab\Component\ComponentStatic;
use Telelab\Router\Router;
use Telelab\Conf\Conf;
use Telelab\Logger\Logger;

/**
 * FrontController: Load route application, execute plugins and controller
 *
 * @author gdievart <dievartg@gmail.com>
 */
class FrontController extends ComponentStatic
{
    /**
     * @var string Name Methods called on plugins
     */
    const PLUGIN_PRECALL = 'precall';
    const PLUGIN_POSTCALL = 'postcall';

    /**
     * @var string Unique id generated by route informations
     */
    protected static $routeId;

    /**
     * @var string Route name
     */
    protected static $routeName;

    /**
     * @var string Controller class name
     */
    protected static $controller;

    /**
     * @var string Method call on controller
     */
    protected static $method;

    /**
     * @var array Args to pass to controller
     */
    protected static $argv = array();

    /**
     * @var array Plugins called
     */
    protected static $plugins = array();

    /**
     * @var array Ref to plugins already loaded
     */
    protected static $pluginsLoaded = array();

    /**
     * @var boolean Flag to interrupt the request
     */
    protected static $interrupRequest = false;

    /**
     * @var string Response
     */
    protected static $response;

    /**
     * Search route, and run application
     */
    public static function run($route = null)
    {
        self::setRouteInfos(self::getRouteInfos($route));
        self::executeRoute();
    }

    /**
     * Get routes informations from Router
     *
     * @param  string $route
     * @return array
     */
    private static function getRouteInfos($route)
    {
        try {
            $router = new Router();
            $routeInfos = $router->getRouteInfos($route);
        } catch (\Telelab\Router\RouterException $e) {
            header("HTTP/1.1 404 Not found");
            if ($error = Conf::getConfig('route_error.404')) {
                self::run($error);
            }
            exit(0);
        }

        return $routeInfos;
    }

    /**
     * Set informations from routeInfos
     *
     * @param array $routeInfos
     */
    protected static function setRouteInfos($routeInfos)
    {
        self::$routeId    = md5(serialize($routeInfos));
        self::$routeName  = $routeInfos['name'];
        self::$argv       = $routeInfos['argv'];

        if (isset($routeInfos['controller'])) {
            if (strpos($routeInfos['controller'], '::') !== false) {
                list(self::$controller, self::$method) = explode('::', $routeInfos['controller']);
            } else {
                self::$controller = $routeInfos['controller'];
                self::$method     = $routeInfos['method'];
            }
        }

        if (isset($routeInfos[self::PLUGIN_PRECALL])) {
            self::$plugins[self::PLUGIN_PRECALL] = $routeInfos[self::PLUGIN_PRECALL];
        } elseif ($precall = Conf::getConfig('plugin.default_precall')) {
            self::$plugins[self::PLUGIN_PRECALL] = $precall;
        } else {
            self::$plugins[self::PLUGIN_PRECALL] = array();
        }

        if (isset($routeInfos[self::PLUGIN_POSTCALL])) {
            self::$plugins[self::PLUGIN_POSTCALL] = $routeInfos[self::PLUGIN_POSTCALL];
        } elseif ($precall = Conf::getConfig('plugin.default_postcall')) {
            self::$plugins[self::PLUGIN_POSTCALL] = $precall;
        } else {
            self::$plugins[self::PLUGIN_POSTCALL] = array();
        }
    }

    /**
     * Execute route
     */
    protected static function executeRoute()
    {
        self::executePlugins(self::PLUGIN_PRECALL);
        self::executeAction();
        self::executePlugins(self::PLUGIN_POSTCALL);
    }

    /**
     * Execute plugins
     *
     * @param string $type
     */
    protected static function executePlugins($method)
    {
        Logger::log('['.__CLASS__.'] excute '.$method.' plugins', Logger::LOG_DEBUG);
        if (!self::$interrupRequest) {
            foreach (self::$plugins[$method] as $plugin) {
                if (empty($plugin)) {
                    continue;
                }

                if (!isset(self::$pluginsLoaded[$plugin])) {
                    self::$pluginsLoaded[$plugin] = new $plugin();
                }

                if ($method === self::PLUGIN_PRECALL) {
                    self::$pluginsLoaded[$plugin]->precall();
                } else {
                    self::$pluginsLoaded[$plugin]->postCall();
                }

                Logger::log('['.__CLASS__.'] excute plugin -> '.$plugin, Logger::LOG_DEBUG);

                if (self::$interrupRequest) {
                    Logger::log('['.__CLASS__.'] interrup request', Logger::LOG_DEBUG);
                    break;
                }
            }
        }
    }

    /**
     * Execute controller
     */
    protected static function executeAction()
    {
        if (!self::$interrupRequest && self::$controller !== null) {
            Logger::log(
                '['.__CLASS__.'] excute action -> '
                .self::$controller.'::'.self::$method.'('.implode(',', self::$argv).')',
                Logger::LOG_DEBUG
            );

            $controller = new self::$controller();
            self::$response = call_user_func_array(
                array($controller, self::$method),
                self::$argv
            );
        } else {
            self::$response = array();
        }
    }

    /**
     * Interrupt request and return response
     */
    public static function interruptRequest()
    {
        self::$interrupRequest = true;
    }

    /**
     * Retrieve route id
     *
     * @return string
     */
    public static function getRouteId()
    {
        return self::$routeId;
    }

    /**
     * Retrieve route name
     *
     * @return string
     */
    public static function getRouteName()
    {
        return self::$routeName;
    }

    /**
     * Retrieve response
     *
     * @return mixed
     */
    public static function getResponse()
    {
        return self::$response;
    }

    /**
     * Set response
     *
     * @param mixed $response
     */
    public static function setResponse($response)
    {
        self::$response = $response;
    }
}
